# Generated by Django 5.0.1 on 2024-01-10 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtext_blogtitle_delete_blog_blogtext_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title_text', models.CharField(max_length=200)),
                ('pub_date', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pub_date', models.TimeField(auto_now_add=True)),
                ('post_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.posttitle')),
            ],
        ),
    ]
