# Generated by Django 5.0.1 on 2024-01-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_posttitle_posttext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtext',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogtitle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posttext',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posttitle',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
